/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPortalDashboardRouteImport } from './routes/app/portal/dashboard'
import { Route as AppAdminDashboardRouteImport } from './routes/app/admin/dashboard'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPortalDashboardRoute = AppPortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/portal/dashboard': typeof AppPortalDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/portal/dashboard': typeof AppPortalDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/portal/dashboard': typeof AppPortalDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/app/admin/dashboard'
    | '/app/portal/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/demo' | '/app/admin/dashboard' | '/app/portal/dashboard'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/app/admin/dashboard'
    | '/app/portal/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/portal/dashboard': {
      id: '/app/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/app/portal/dashboard'
      preLoaderRoute: typeof AppPortalDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppPortalDashboardRoute: typeof AppPortalDashboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppPortalDashboardRoute: AppPortalDashboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DemoRoute: DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
