/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppAppDashboardRouteImport } from './routes/app/app/dashboard'
import { Route as AppAdminDashboardRouteImport } from './routes/app/admin/dashboard'

const IndexLazyRouteImport = createFileRoute('/')()

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/app/dashboard': typeof AppAppDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/app/dashboard': typeof AppAppDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/app/dashboard': typeof AppAppDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/admin/dashboard' | '/app/app/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/admin/dashboard' | '/app/app/dashboard'
  id: '__root__' | '/' | '/app' | '/app/admin/dashboard' | '/app/app/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/app/dashboard': {
      id: '/app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAppDashboardRoute: typeof AppAppDashboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAppDashboardRoute: AppAppDashboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
